name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:8.0
        ports:
          - 27017:27017

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup pnpm
      uses: pnpm/action-setup@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'pnpm'
    
    - name: Install dependencies
      run: pnpm install
    
    - name: Build packages
      run: pnpm -r build
    
    - name: Cache build artifacts
      uses: actions/cache/save@v4
      with:
        path: |
          packages/*/dist
          meal-rec/.next
        key: build-artifacts-${{ github.sha }}
    
    - name: Run lint
      run: pnpm lint
    
    - name: Run tests
      run: pnpm test
      env:
        MONGO_URL: mongodb://localhost:27017/meal-rec-test
        NEXTAUTH_SECRET: test-secret-for-ci-only
        NEXTAUTH_URL: http://localhost:3000
    
    - name: Test seed script (dry run)
      run: pnpm seed --dry-run

  e2e:
    runs-on: ubuntu-latest
    needs: test
    if: "!contains(github.event.head_commit.message, '[skip e2e]')"

    services:
      mongodb:
        image: mongo:8.0
        ports:
          - 27017:27017

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup pnpm
      uses: pnpm/action-setup@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'pnpm'
    
    - name: Install dependencies
      run: pnpm install
    
    - name: Restore build artifacts
      uses: actions/cache/restore@v4
      with:
        path: |
          packages/*/dist
          meal-rec/.next
        key: build-artifacts-${{ github.sha }}
        fail-on-cache-miss: true
    
    - name: Cache Playwright browsers
      uses: actions/cache@v4
      with:
        path: ~/.cache/ms-playwright
        key: playwright-browsers-${{ hashFiles('meal-rec/package.json') }}
    
    - name: Install Playwright Browsers
      run: cd meal-rec && pnpm exec playwright install --with-deps
    
    - name: Run E2E tests
      run: cd meal-rec && pnpm test:e2e
      env:
        NEXTAUTH_SECRET: test-secret-for-ci-only
        NEXTAUTH_URL: http://localhost:3000
        MONGO_URL: mongodb://localhost:27017/meal-rec-e2e-test
    
    - name: Upload E2E test results
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: e2e-test-results
        path: meal-rec/test-results/

  lighthouse:
    runs-on: ubuntu-latest
    needs: test
    if: contains(github.event.pull_request.labels.*.name, 'performance')

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup pnpm
      uses: pnpm/action-setup@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'pnpm'
    
    - name: Install dependencies
      run: pnpm install
    
    - name: Restore build artifacts
      uses: actions/cache/restore@v4
      with:
        path: |
          packages/*/dist
          meal-rec/.next
        key: build-artifacts-${{ github.sha }}
        fail-on-cache-miss: true
    
    - name: Run Lighthouse CI
      run: cd meal-rec && pnpm lighthouse
    
    - name: Upload Lighthouse results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: lighthouse-results
        path: meal-rec/.lighthouseci/

